"""Regenerate results/reports/vision.md from results/runs/V*.json (spec 2026-09-16 §8).

Idempotent and disposable, like build_reports.py: the run files are the source of truth. One seed
means point differences only — no verdict machinery lives here.

Usage: uv run python scripts/build_vision_report.py [--results results]
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

from hallm.results import read_run_results

STAMP = "<!-- GENERATED by scripts/build_vision_report.py from results/runs/V*.json — do not edit -->"

ARMS = ["V4-A0", "V8-A0", "V8-A2", "V8-A1u4", "V8-A1u4t"]
# (a, b, kind): a's top-1 minus b's, in percentage points. Positive = a is better.
PAIRS = [
    ("V8-A1u4", "V4-A0", "iso-storage"),
    ("V8-A2", "V4-A0", "iso-storage"),
    ("V8-A1u4", "V8-A2", "matched storage and compute"),
    ("V8-A1u4t", "V8-A1u4", "matched storage and compute"),
]


_REQUIRED_FIELDS = ("arm", "n_layer", "non_embedding_params_M", "top1", "val_loss")


def _by_arm(rows: list[dict]) -> dict[str, dict]:
    """Index vision rows by arm name (run id minus the -s<seed> suffix).

    Guards the fields the table and pairs sections read — a V-prefixed row missing one would
    otherwise raise a bare KeyError deep inside the ARMS loop and kill generation of the whole
    report rather than just that row. Real rows always carry these (write_run_result only runs
    after eval completes); this defends against a future partial or hand-edited result file."""
    seen: dict[str, dict] = {}
    for r in rows:
        if not r["run"].startswith("V"):
            continue
        missing = [f for f in _REQUIRED_FIELDS if f not in r]
        if missing:
            raise ValueError(
                f"vision row {r['run']!r} missing required field(s): {', '.join(missing)} "
                "— partial or hand-edited result file?")
        seen[r["run"].rsplit("-s", 1)[0]] = r
    return seen


def vision_report(rows: list[dict]) -> str:
    seen = _by_arm(rows)
    out = [STAMP, "# Controlled ViT study (spec 2026-09-16)", ""]
    out.append("ImageNet-100 @112px, one recipe across arms, **1 seed (1337) — descriptive only, "
               "no verdict is claimed**. Δ is a top-1 point difference; positive means the first "
               "model is better.")
    out += ["", "| run | arm | layers | stored non-emb M | top-1 | val loss |", "|---|---|---|---|---|---|"]
    for name in ARMS:
        r = seen.get(name)
        if r is None:
            out.append(f"| {name} | — | — | — | pending | pending |")
        else:
            out.append(f"| {r['run']} | {r['arm']} | {r['n_layer']} | "
                       f"{r['non_embedding_params_M']:.2f} | {100 * r['top1']:.1f} | "
                       f"{r['val_loss']:.4f} |")

    out += ["", "## Pairs", "", "| a | b | kind | top-1 a / b | Δ points | note |",
            "|---|---|---|---|---|---|"]
    for a, b, kind in PAIRS:
        ra, rb = seen.get(a), seen.get(b)
        if ra is None or rb is None:
            out.append(f"| {a} | {b} | {kind} | — | — | pending |")
            continue
        delta = 100 * (ra["top1"] - rb["top1"])
        note = ""
        if abs(ra["non_embedding_params_M"] - rb["non_embedding_params_M"]) > 0.01:
            note = "**storage mismatch** — the pairing is not iso-storage"
        out.append(f"| {a} | {b} | {kind} | {100 * ra['top1']:.1f} / {100 * rb['top1']:.1f} | "
                   f"{delta:+.1f} | {note} |")

    deep, shallow = seen.get("V8-A0"), seen.get("V4-A0")
    if deep and shallow:
        ok = deep["top1"] > shallow["top1"]
        verdict = "pass" if ok else "**FAIL — the setup cannot say anything about sharing**"
        out += ["", f"**Depth gate (spec §3):** V8-A0 {100 * deep['top1']:.1f} vs V4-A0 "
                    f"{100 * shallow['top1']:.1f} → {verdict}"]
    else:
        out += ["", "**Depth gate (spec §3):** pending"]

    a2, v4 = seen.get("V8-A2"), seen.get("V4-A0")
    if a2 and v4:
        gap = abs(100 * (a2["top1"] - v4["top1"]))
        follow = ("triggered — run seeds 1338/1339 for V8-A2, V4-A0 and V8-A1u4"
                  if gap >= 1.0 else "not triggered — reported as no difference detected at 1 seed")
        out += ["", f"**Follow-up seed rule (spec §3):** |Δ| = {gap:.1f} points → {follow}"]
    else:
        out += ["", "**Follow-up seed rule (spec §3):** pending"]
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    args = ap.parse_args()
    rows = read_run_results(Path(args.results) / "runs")
    path = Path(args.results) / "reports" / "vision.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    text = vision_report(rows) + f"\n<!-- built {stamp} from {len(rows)} run(s) -->\n"
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
