"""Regenerate every comparison table from per-run result files.

Idempotent and disposable: delete results/reports/*.md and re-run to rebuild. Nothing here is a
source of truth — results/runs/<run-id>.json is.

Usage: uv run python scripts/build_reports.py [--results results]
"""

from __future__ import annotations

import argparse
import math
from datetime import datetime, timezone
from pathlib import Path

from hallm.reports import hs_verdict, index_runs, mean_se, regress, tax
from hallm.results import read_run_results

STAMP = "<!-- GENERATED by scripts/build_reports.py from results/runs/*.json — do not edit -->"
# Per-layer non-embedding storage in units of d^2: attention 4, FFN 8.
STORAGE_SAVED = {"A2": 50.0, "A2ffn": 33.3, "A2attn": 16.7, "A1": 87.5, "A3": 93.7}


def _f(v, nd=2, dash="—"):
    return dash if v is None or (isinstance(v, float) and math.isnan(v)) else f"{v:.{nd}f}"


def build_ladder(rows: list[dict]) -> str:
    idx = index_runs(rows)
    L = [STAMP, "# Scaling ladder — sharing tax vs depth", "",
         "Tax = (PPL_shared - PPL_unshared) / PPL_unshared, measured **within** a seed pair.", "",
         "| rung | seed | A0 (unshared) | A2 (W+Wt) | tax % |", "|---|---|---|---|---|"]
    per_rung: dict[int, list[float]] = {}
    pts_x: list[float] = []
    pts_y: list[float] = []
    for (depth, seed) in sorted(idx):
        arms = idx[(depth, seed)]
        a0, a2 = arms.get("A0"), arms.get("A2")
        if not a0:
            continue
        if not a2:
            L.append(f"| L{depth} | {seed} | {a0['test_ppl']:.4f} | *(pending)* | — |")
            continue
        t = tax(a2["test_ppl"], a0["test_ppl"])
        per_rung.setdefault(depth, []).append(t)
        nonemb = a0.get("non_embedding_params_M")
        if nonemb:
            pts_x.append(math.log2(nonemb))
            pts_y.append(t)
        L.append(f"| L{depth} | {seed} | {a0['test_ppl']:.4f} | {a2['test_ppl']:.4f} | **{t:.2f}** |")

    L += ["", "## Per-rung summary", "",
          "| rung | n seeds | mean tax % | SE |", "|---|---|---|---|"]
    for depth in sorted(per_rung):
        m, se = mean_se(per_rung[depth])
        L.append(f"| L{depth} | {len(per_rung[depth])} | {m:.2f} | {_f(se)} |")

    reg = regress(pts_x, pts_y)
    L += ["", "## H-S: does the tax decay with scale?", "",
          "Pre-registered decision rule (program spec P3): regress tax on log2(non-embedding params);",
          "**supported** iff the slope's 95% CI excludes zero on the negative side.", ""]
    if reg["n"] >= 3:
        L += [f"- points: **{reg['n']}** pairs",
              f"- slope: **{reg['slope']:.2f} pp** per doubling of non-embedding params",
              f"- 95% CI: [{reg['ci_lo']:.2f}, {reg['ci_hi']:.2f}]  (df={reg['df']})",
              f"- **verdict: {hs_verdict(reg)}**"]
        if reg["slope"] < 0 and reg.get("intercept") is not None:
            need = 2 ** ((reg["intercept"] - 2.0) / -reg["slope"]) if reg["slope"] else float("inf")
            L += ["", f"Extrapolated non-embedding size for a <2% tax: **{need:,.0f}M params**. "
                      "Reported to keep the decay honest — the ladder characterises a rate, it does "
                      "not lead to the viability gate."]
    else:
        L.append(f"- insufficient data ({reg['n']} complete pairs; need 3)")
    return "\n".join(L) + "\n"


def build_mechanism(rows: list[dict]) -> str:
    """P1: which sublayer's sharing causes the tax?"""
    idx = index_runs(rows)
    L = [STAMP, "# Mechanism decomposition (P1) — where does the tax come from?", "",
         "FFN sharing has a genuine nonlinearity between W and W-transpose (strong column-space",
         "argument). Attention sharing has K and V both linear in the same x, and couples the QK and",
         "OV circuits (weak path, risk R1). Pre-registered: tax(attn-only) > tax(ffn-only) by >2pp.",
         "", "| rung | seed | arm | PPL | tax % | storage saved % | cost per % saved |",
         "|---|---|---|---|---|---|---|"]
    found = False
    per_arm: dict[str, list[float]] = {}
    for (depth, seed) in sorted(idx):
        arms = idx[(depth, seed)]
        a0 = arms.get("A0")
        if not a0:
            continue
        for tag in ("A2", "A2ffn", "A2attn"):
            row = arms.get(tag)
            if not row:
                continue
            found = True
            t = tax(row["test_ppl"], a0["test_ppl"])
            per_arm.setdefault(tag, []).append(t)
            saved = STORAGE_SAVED.get(tag)
            ratio = t / saved if saved else float("nan")
            L.append(f"| L{depth} | {seed} | {tag} | {row['test_ppl']:.4f} | {t:.2f} | "
                     f"{_f(saved, 1)} | {_f(ratio, 3)} |")
    if not found:
        L.append("| — | — | — | — | — | — | — |")
        L += ["", "*No ablation runs complete yet.*"]
        return "\n".join(L) + "\n"

    L += ["", "## Verdict", ""]
    ffn, attn, both = per_arm.get("A2ffn"), per_arm.get("A2attn"), per_arm.get("A2")
    if ffn and attn:
        mf, _ = mean_se(ffn)
        ma, _ = mean_se(attn)
        L.append(f"- mean tax: FFN-only **{mf:.2f}%**, attn-only **{ma:.2f}%** "
                 f"(difference {ma - mf:+.2f} pp)")
        L.append(f"- **H-M1 ({'supported' if ma - mf > 2 else 'not supported'})**: "
                 "attention sharing costs more than FFN sharing by >2pp")
        if both:
            mb, _ = mean_se(both)
            L.append(f"- **H-M2 ({'supported' if abs(mb - (mf + ma)) < 2 else 'not supported'})**: "
                     f"taxes are additive — A2 {mb:.2f}% vs ffn+attn {mf + ma:.2f}%")
        best = min(("A2ffn", mf / STORAGE_SAVED["A2ffn"]), ("A2attn", ma / STORAGE_SAVED["A2attn"]),
                   key=lambda kv: kv[1])
        L.append(f"- best cost-per-%-storage-saved: **{best[0]}** at {best[1]:.3f} "
                 "(A2 baseline 0.278, ALBERT 0.420)")
    else:
        L.append("- decomposition incomplete: need both A2ffn and A2attn at a shared seed.")
    return "\n".join(L) + "\n"


def build_memory(rows: list[dict]) -> str:
    L = [STAMP, "# Memory accounting", "",
         "Sharing compresses **weights only** — the KV cache is 2*d*L per token regardless. This is",
         "why re-investing shared weights into depth pays the saving back in cache.", "",
         "| run | weight MB (bf16) | KV MB @ctx512 b1 | KV MB @ctx2048 b8 | weight share @ctx512 |",
         "|---|---|---|---|---|"]
    any_row = False
    for r in rows:
        if "weight_bytes_bf16" not in r:
            continue
        any_row = True
        L.append(f"| {r['run']} | {r['weight_bytes_bf16']/1e6:.1f} | "
                 f"{r['kv_bytes_ctx512_b1']/1e6:.1f} | {r['kv_bytes_ctx2048_b8']/1e6:.1f} | "
                 f"{r['weight_frac_of_total_ctx512_b1']*100:.1f}% |")
    if not any_row:
        L.append("| — | — | — | — | — |")
        L += ["", "*No run carries measured memory yet (pre-P0 runs did not record it).*"]
    return "\n".join(L) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="results")
    args = ap.parse_args()
    results = Path(args.results)
    rows = read_run_results(results / "runs")
    out = results / "reports"
    out.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    for name, text in (("ladder.md", build_ladder(rows)),
                       ("mechanism.md", build_mechanism(rows)),
                       ("memory.md", build_memory(rows))):
        (out / name).write_text(text + f"\n<!-- built {stamp} from {len(rows)} run(s) -->\n",
                                encoding="utf-8")
        print(f"wrote {out / name}")


if __name__ == "__main__":
    main()
