"""Regenerate results/reports/vision.md from results/runs/V*.json (spec 2026-09-16 §8).

Idempotent and disposable, like build_reports.py: the run files are the source of truth. One seed
means point differences only — no verdict machinery lives here.

Usage: uv run python scripts/build_vision_report.py [--results results] [--runs-dir runs/vision]
       [--seed 1337]
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from hallm.manifest import manifest_diff
from hallm.results import read_run_results

STAMP = "<!-- GENERATED by scripts/build_vision_report.py from results/runs/V*.json — do not edit -->"

ARMS = ["V4-A0", "V8-A0", "V8-A2", "V8-A1u4", "V8-A1u4t"]
# (a, b, kind): a's top-1 minus b's, in percentage points. Positive = a is better.
PAIRS = [
    ("V8-A1u4", "V4-A0", "iso-storage"),
    ("V8-A2", "V4-A0", "iso-storage"),
    ("V8-A1u4", "V8-A2", "matched storage and compute"),
    ("V8-A1u4t", "V8-A1u4", "matched storage and compute"),
]


_REQUIRED_FIELDS = ("arm", "n_layer", "non_embedding_params_M", "top1", "val_loss")


def _by_arm(rows: list[dict], seed: int) -> dict[str, dict]:
    """Index vision rows by arm name (run id minus the -s<seed> suffix), keeping only rows for
    `seed`.

    Guards the fields the table and pairs sections read — a V-prefixed row missing one would
    otherwise raise a bare KeyError deep inside the ARMS loop and kill generation of the whole
    report rather than just that row. Real rows always carry these (write_run_result only runs
    after eval completes); this defends against a future partial or hand-edited result file.

    The seed filter matters once follow-up seeds land: `read_run_results` returns rows sorted by
    run id, so without filtering, keying purely by arm would let whichever seed sorts last (e.g.
    s1339) silently overwrite s1337 here while the header kept naming 1337 — the report would name
    one seed and show another's numbers. Filtering to `seed` up front makes that impossible."""
    seen: dict[str, dict] = {}
    suffix = f"-s{seed}"
    for r in rows:
        if not r["run"].startswith("V"):
            continue
        missing = [f for f in _REQUIRED_FIELDS if f not in r]
        if missing:
            raise ValueError(
                f"vision row {r['run']!r} missing required field(s): {', '.join(missing)} "
                "— partial or hand-edited result file?")
        if not r["run"].endswith(suffix):
            continue
        seen[r["run"].rsplit("-s", 1)[0]] = r
    return seen


def _protocol_section(manifests: dict[str, dict | None]) -> list[str]:
    """`## Protocol` section: diffs each arm's frozen manifest against the first available one, so
    the report carries positive evidence that the five arms actually shared one protocol rather
    than just asserting it.

    Degrades gracefully — manifests land one run at a time as the queue finishes, so most of the
    time only some of the five exist. Never raises: absent manifests print as "pending", never a
    KeyError or a crash of the whole report."""
    out = ["", "## Protocol", "",
          "Each arm's frozen `manifest.json` diffed against the first available arm's "
          "(environment keys — timestamp, GPU, platform, config path — excluded; only the declared "
          "variables and any accidental drift would show up here)."]
    have = {arm: m for arm in ARMS if (m := manifests.get(arm)) is not None}
    if not have:
        out += ["", "pending — no manifests written yet."]
        return out
    ref_arm, ref = next(iter(have.items()))
    out += ["", f"Reference: `{ref_arm}`.", "",
           "| arm | differing keys (vs. reference) |", "|---|---|"]
    for arm in ARMS:
        m = manifests.get(arm)
        if m is None:
            out.append(f"| {arm} | pending |")
        elif arm == ref_arm:
            out.append(f"| {arm} | — (reference) |")
        else:
            diff = manifest_diff(ref, m)
            out.append(f"| {arm} | {', '.join(sorted(diff)) if diff else 'none'} |")

    if len(have) >= 2:
        ident = "yes" if all(m.get("data_sha256") == ref.get("data_sha256") for m in have.values()) else "no"
    else:
        ident = "pending — fewer than two manifests present"
    out += ["", f"**Data hashes identical across arms:** {ident}"]
    return out


def vision_report(rows: list[dict], seed: int = 1337, manifests: dict[str, dict | None] | None = None) -> str:
    seen = _by_arm(rows, seed)
    out = [STAMP, "# Controlled ViT study (spec 2026-09-16)", ""]
    out.append(f"ImageNet-100 @112px, one recipe across arms, **1 seed ({seed}) — descriptive only, "
               "no verdict is claimed**. Δ is a top-1 point difference; positive means the first "
               "model is better.")
    out.append("")
    out.append(
        "**Reading these numbers (spec §3, §4, §9 R3).** With 100 classes, random guessing scores "
        "~1% top-1; every arm reported below is expected to land clearly above that floor, not "
        "merely above it. Separately, the augmentation floor used here — a random crop and flip, "
        "nothing else — is deliberately minimal and is *not* HaLViT's published training recipe, "
        "so absolute top-1 numbers are expected to sit below published ImageNet-100 results; a null "
        "result in this report therefore shows that the sharing gain does not survive a common, "
        "minimal recipe, not that it fails HaLViT's own recipe on its own terms. The third §3 "
        "sanity gate — V8-A2's FFN Jacobian rotation share measuring ~0 — is not repeated here; "
        "see `results/reports/ffn-symmetry.md`."
    )
    out += ["", "| run | arm | layers | stored non-emb M | top-1 | val loss |", "|---|---|---|---|---|---|"]
    for name in ARMS:
        r = seen.get(name)
        if r is None:
            out.append(f"| {name} | — | — | — | pending | pending |")
        else:
            out.append(f"| {r['run']} | {r['arm']} | {r['n_layer']} | "
                       f"{r['non_embedding_params_M']:.2f} | {100 * r['top1']:.1f} | "
                       f"{r['val_loss']:.4f} |")

    out += ["", "## Pairs", "", "| a | b | kind | top-1 a / b | Δ points | note |",
            "|---|---|---|---|---|---|"]
    for a, b, kind in PAIRS:
        ra, rb = seen.get(a), seen.get(b)
        if ra is None or rb is None:
            out.append(f"| {a} | {b} | {kind} | — | — | pending |")
            continue
        delta = 100 * (ra["top1"] - rb["top1"])
        note = ""
        if abs(ra["non_embedding_params_M"] - rb["non_embedding_params_M"]) > 0.01:
            note = "**storage mismatch** — the pairing is not iso-storage"
        out.append(f"| {a} | {b} | {kind} | {100 * ra['top1']:.1f} / {100 * rb['top1']:.1f} | "
                   f"{delta:+.1f} | {note} |")

    deep, shallow = seen.get("V8-A0"), seen.get("V4-A0")
    if deep and shallow:
        ok = deep["top1"] > shallow["top1"]
        verdict = "pass" if ok else "**FAIL — the setup cannot say anything about sharing**"
        out += ["", f"**Depth gate (spec §3):** V8-A0 {100 * deep['top1']:.1f} vs V4-A0 "
                    f"{100 * shallow['top1']:.1f} → {verdict}"]
    else:
        out += ["", "**Depth gate (spec §3):** pending"]

    a2, v4 = seen.get("V8-A2"), seen.get("V4-A0")
    if a2 and v4:
        gap = abs(100 * (a2["top1"] - v4["top1"]))
        # top1 is correct/N_images, so an exact 1.0-point gap (e.g. 50/5000 images) can land as
        # 0.9999999999999953 in float — compare with a tolerance so a mathematically-exact gap
        # always triggers regardless of how the subtraction happens to round.
        follow = ("triggered — run seeds 1338/1339 for V8-A2, V4-A0 and V8-A1u4"
                  if gap >= 1.0 - 1e-9 else "not triggered — reported as no difference detected at 1 seed")
        # Two decimals here (unlike the pairs table's one) so the printed number never contradicts
        # the decision next to it — e.g. a genuine 0.96-point gap must not read as "1.0 points".
        out += ["", f"**Follow-up seed rule (spec §3):** |Δ| = {gap:.2f} points → {follow}"]
    else:
        out += ["", "**Follow-up seed rule (spec §3):** pending"]

    out += _protocol_section(manifests or {})
    return "\n".join(out) + "\n"


def _load_manifests(runs_dir: Path, seed: int) -> dict[str, dict | None]:
    """One manifest per arm for `seed`, or None where the run hasn't landed (or launched) yet.
    Manifests are frozen write-once files (spec 2026-09-16 §8.2 / `hallm.manifest`), so reading
    them here is safe even while the training queue is running."""
    manifests: dict[str, dict | None] = {}
    for arm in ARMS:
        p = runs_dir / f"{arm}-s{seed}" / "manifest.json"
        if not p.exists():
            manifests[arm] = None
            continue
        try:
            manifests[arm] = json.loads(p.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            manifests[arm] = None
    return manifests


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--runs-dir", default="runs/vision")
    ap.add_argument("--seed", type=int, default=1337)
    args = ap.parse_args()
    rows = read_run_results(Path(args.results) / "runs")
    manifests = _load_manifests(Path(args.runs_dir), args.seed)
    path = Path(args.results) / "reports" / "vision.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    text = (vision_report(rows, seed=args.seed, manifests=manifests)
           + f"\n<!-- built {stamp} from {len(rows)} run(s) -->\n")
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
