"""Regenerate results/reports/vision.md from results/runs/V*.json (spec 2026-09-16 §8).

Idempotent and disposable, like build_reports.py: the run files are the source of truth. One seed
means point differences only — no verdict machinery lives here.

Usage: uv run python scripts/build_vision_report.py [--results results] [--runs-dir runs/vision]
       [--seed 1337]
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path

from hallm.manifest import manifest_diff
from hallm.results import read_run_results

STAMP = "<!-- GENERATED by scripts/build_vision_report.py from results/runs/V*.json — do not edit -->"

ARMS = ["V4-A0", "V8-A0", "V8-A2", "V8-A1u4", "V8-A1u4t"]
# (a, b, kind): a's top-1 minus b's, in percentage points. Positive = a is better.
PAIRS = [
    ("V8-A1u4", "V4-A0", "iso-storage"),
    ("V8-A2", "V4-A0", "iso-storage"),
    ("V8-A1u4", "V8-A2", "matched storage and compute"),
    ("V8-A1u4t", "V8-A1u4", "matched storage and compute"),
]


_REQUIRED_FIELDS = ("arm", "n_layer", "non_embedding_params_M", "top1", "val_loss")


def overfit_flag(top1: float, top1_best: float | None, threshold: float = 0.01) -> str:
    """Spec 2026-09-18 §7: an arm whose best periodic top-1 exceeds its final by more than
    `threshold` (1.0 point) is disclosed as still overfitting rather than reported at its peak."""
    if top1_best is None:
        return ""
    return "still overfitting" if (top1_best - top1) > threshold else ""


# run ids look like `<arm>-s<seed>` (ImageNet-100, e.g. `V4-A0-s1337`) or `<arm>-s<seed>-in1k`
# (ImageNet-1k, e.g. `V4-A0-s1337-in1k`) — arm and seed are always present, an optional single
# alphanumeric suffix comes after the seed.
_RUN_ID_RE = re.compile(r"^(?P<arm>.+)-s(?P<seed>\d+)(?:-(?P<suffix>[A-Za-z0-9]+))?$")

# Suffix -> corpus for the two passes this report covers. `None` (no suffix) is the original
# ImageNet-100 pass; `"in1k"` is the new ImageNet-1k pass. Any OTHER suffix — e.g. `-p5k`
# diagnostic probe runs (spec 2026-09-18 §7, excluded by spec), or `-fw`/`-d360`/`-lr2x` ablations
# that exist elsewhere in this repo's run ids — is not one of these two report corpora, so
# `_parse_run_id` returns None for it rather than guessing. This is what keeps a probe row out of
# the report even if it ever ended up in results/runs/ instead of results/probes/: the exclusion
# comes from parsing the id, not from which directory the file happened to be read from.
_CORPUS_BY_SUFFIX = {None: "imagenet-100", "in1k": "imagenet-1k"}


def _parse_run_id(run: str, seed: int) -> tuple[str, str] | None:
    """(arm, corpus) for a vision run id belonging to `seed` and one of this report's two
    corpora — or None if `run` doesn't match `seed` or carries a suffix outside
    `_CORPUS_BY_SUFFIX` (so it is excluded rather than merged into either block).

    Arm identity and corpus both live inside the run id, so both must come out of one parse:
    stripping only the `-s<seed>` suffix (as the previous implementation did via
    `rsplit("-s", 1)`) maps `V4-A0-s1337` and `V4-A0-s1337-in1k` to the same arm key, which is
    exactly the collision that let ImageNet-1k rows silently overwrite ImageNet-100 rows (or vice
    versa, depending on dict insertion order) for the same arm."""
    m = _RUN_ID_RE.match(run)
    if m is None or int(m.group("seed")) != seed:
        return None
    corpus = _CORPUS_BY_SUFFIX.get(m.group("suffix"))
    if corpus is None:
        return None
    return m.group("arm"), corpus


def _by_arm(rows: list[dict], seed: int) -> dict[str, dict[str, dict]]:
    """Index vision rows as {arm: {corpus: row}}, keeping only rows for `seed` and for one of
    this report's two corpora (see `_parse_run_id`).

    Guards the fields the table and pairs sections read — a V-prefixed row missing one would
    otherwise raise a bare KeyError deep inside the ARMS loop and kill generation of the whole
    report rather than just that row. Real rows always carry these (write_run_result only runs
    after eval completes); this defends against a future partial or hand-edited result file.

    Keying by (arm, corpus) rather than by arm alone is what lets the same arm carry both an
    ImageNet-100 and an ImageNet-1k row at once — with arm-only keying (the previous
    implementation), whichever corpus's row landed last in `rows` (which `read_run_results` sorts
    by run id) would silently clobber the other in `seen`, and the seed filter alone additionally
    dropped every `-in1k` row before it ever got that far. Filtering to `seed` up front also keeps
    a later seed (e.g. s1339) from silently overwriting s1337 while the header still names 1337."""
    seen: dict[str, dict[str, dict]] = {}
    for r in rows:
        if not r["run"].startswith("V"):
            continue
        missing = [f for f in _REQUIRED_FIELDS if f not in r]
        if missing:
            raise ValueError(
                f"vision row {r['run']!r} missing required field(s): {', '.join(missing)} "
                "— partial or hand-edited result file?")
        parsed = _parse_run_id(r["run"], seed)
        if parsed is None:
            continue
        arm, corpus = parsed
        seen.setdefault(arm, {})[corpus] = r
    return seen


def _protocol_section(manifests: dict[str, dict | None]) -> list[str]:
    """`## Protocol` section: diffs each arm's frozen manifest against the first available one, so
    the report carries positive evidence that the five arms actually shared one protocol rather
    than just asserting it.

    Degrades gracefully — manifests land one run at a time as the queue finishes, so most of the
    time only some of the five exist. Never raises: absent manifests print as "pending", never a
    KeyError or a crash of the whole report."""
    out = ["", "## Protocol", "",
          "Each arm's frozen `manifest.json` diffed against the first available arm's "
          "(environment keys — timestamp, GPU, platform, config path — excluded; only the declared "
          "variables and any accidental drift would show up here)."]
    have = {arm: m for arm in ARMS if (m := manifests.get(arm)) is not None}
    if not have:
        out += ["", "pending — no manifests written yet."]
        return out
    ref_arm, ref = next(iter(have.items()))
    out += ["", f"Reference: `{ref_arm}`.", "",
           "| arm | differing keys (vs. reference) |", "|---|---|"]
    for arm in ARMS:
        m = manifests.get(arm)
        if m is None:
            out.append(f"| {arm} | pending |")
        elif arm == ref_arm:
            out.append(f"| {arm} | — (reference) |")
        else:
            diff = manifest_diff(ref, m)
            out.append(f"| {arm} | {', '.join(sorted(diff)) if diff else 'none'} |")

    if len(have) >= 2:
        ident = "yes" if all(m.get("data_sha256") == ref.get("data_sha256") for m in have.values()) else "no"
    else:
        ident = "pending — fewer than two manifests present"
    out += ["", f"**Data hashes identical across arms:** {ident}"]
    return out


def _uniform_or_mixed(block_rows: list[dict], field: str) -> str:
    """The block header's `field` value if every landed row in the block agrees, `"mixed"` if
    they disagree, or `"—"` if no row has landed yet (or none carries the field).

    Guards against silently reporting one arbitrary arm's value as if it applied to the whole
    block (Minor finding, review 2026-09-18) — e.g. a block whose arms disagree on `n_classes`
    would previously print whichever row happened to be `next()`-ed first as if it spoke for the
    entire block."""
    if not block_rows:
        return "—"
    values = {r.get(field) for r in block_rows}
    if len(values) > 1:
        return "mixed"
    value = next(iter(values))
    return "—" if value is None else value


def vision_report(rows: list[dict], seed: int = 1337, manifests: dict[str, dict | None] | None = None) -> str:
    seen = _by_arm(rows, seed)

    def im100(name: str) -> dict | None:
        # Pairs / depth gate / follow-up-seed rule are all pre-existing, single-corpus concepts
        # (spec 2026-09-16 §3) — they read the original ImageNet-100 pass specifically, not
        # "whichever corpus happens to be in `seen`".
        return seen.get(name, {}).get("imagenet-100")

    out = [STAMP, "# Controlled ViT study (spec 2026-09-16)", ""]
    out.append(f"ImageNet-100 @112px, one recipe across arms, **1 seed ({seed}) — descriptive only, "
               "no verdict is claimed**. Δ is a top-1 point difference; positive means the first "
               "model is better.")
    out.append("")
    out.append(
        "**Reading these numbers (spec §3, §4, §9 R3).** With 100 classes, random guessing scores "
        "~1% top-1; every arm reported below is expected to land clearly above that floor, not "
        "merely above it. Separately, the augmentation floor used here — a random crop and flip, "
        "nothing else — is deliberately minimal and is *not* HaLViT's published training recipe, "
        "so absolute top-1 numbers are expected to sit below published ImageNet-100 results; a null "
        "result in this report therefore shows that the sharing gain does not survive a common, "
        "minimal recipe, not that it fails HaLViT's own recipe on its own terms. The third §3 "
        "sanity gate — V8-A2's FFN Jacobian rotation share measuring ~0 — is not repeated here; "
        "see `results/reports/ffn-symmetry.md`."
    )
    # Group arms by corpus (spec 2026-09-18 §7): the two passes run the same five arms over
    # different corpora and are not comparable to each other, so each corpus gets its own labelled
    # block rather than one shared table. `_by_arm` only ever returns "imagenet-100" or
    # "imagenet-1k" as a corpus (see `_CORPUS_BY_SUFFIX`), so listing both explicitly — in this
    # fixed, meaningful order — rather than deriving the set from `seen` keeps block order stable
    # even before any arm has landed for a corpus. Every block lists all five ARMS regardless of
    # how many have landed for it, missing ones rendering as "pending" below (unchanged from
    # before this fix); with no rows at all, only "imagenet-100" is shown, matching prior behavior.
    corpus_order = ["imagenet-100", "imagenet-1k"]
    landed_corpora = {c for arm_rows in seen.values() for c in arm_rows}
    corpora = [c for c in corpus_order if c in landed_corpora] or ["imagenet-100"]
    blocks: dict[str, list[str]] = {corpus: list(ARMS) for corpus in corpora}

    table_header = ["| run | arm | layers | stored non-emb M | top-1 | val loss | corpus | passes "
                    "| top-1 best | best step | flag |",
                   "|---|---|---|---|---|---|---|---|---|---|---|"]
    for corpus, names in blocks.items():
        block_rows = [seen[n][corpus] for n in names if corpus in seen.get(n, {})]
        n_classes = _uniform_or_mixed(block_rows, "n_classes")
        passes_header = _uniform_or_mixed(block_rows, "passes")
        out += ["", f"### {corpus} — {n_classes}-way, {passes_header} passes over the corpus", "",
               "> 1 seed (1337), descriptive. Absolute accuracies are NOT comparable across "
               "blocks: the blocks differ in corpus, class count and pass count. Only arm gaps "
               "within a block are claimed."]
        out += ["", *table_header]
        for name in names:
            r = seen.get(name, {}).get(corpus)
            if r is None:
                out.append(f"| {name} | — | — | — | pending | pending | {corpus} | — | — | — | |")
                continue
            passes_cell = "—" if r.get("passes") is None else r["passes"]
            top1_best = r.get("top1_best")
            top1_best_cell = "—" if top1_best is None else f"{100 * top1_best:.1f}"
            best_step_cell = "—" if r.get("best_step") is None else r["best_step"]
            out.append(f"| {r['run']} | {r['arm']} | {r['n_layer']} | "
                       f"{r['non_embedding_params_M']:.2f} | {100 * r['top1']:.1f} | "
                       f"{r['val_loss']:.4f} | {r.get('corpus') or 'imagenet-100'} | "
                       f"{passes_cell} | {top1_best_cell} | {best_step_cell} | "
                       f"{overfit_flag(r['top1'], top1_best)} |")

    out += ["", "## Pairs", "", "| a | b | kind | top-1 a / b | Δ points | note |",
            "|---|---|---|---|---|---|"]
    for a, b, kind in PAIRS:
        ra, rb = im100(a), im100(b)
        if ra is None or rb is None:
            out.append(f"| {a} | {b} | {kind} | — | — | pending |")
            continue
        delta = 100 * (ra["top1"] - rb["top1"])
        note = ""
        if abs(ra["non_embedding_params_M"] - rb["non_embedding_params_M"]) > 0.01:
            note = "**storage mismatch** — the pairing is not iso-storage"
        out.append(f"| {a} | {b} | {kind} | {100 * ra['top1']:.1f} / {100 * rb['top1']:.1f} | "
                   f"{delta:+.1f} | {note} |")

    deep, shallow = im100("V8-A0"), im100("V4-A0")
    if deep and shallow:
        ok = deep["top1"] > shallow["top1"]
        verdict = "pass" if ok else "**FAIL — the setup cannot say anything about sharing**"
        out += ["", f"**Depth gate (spec §3):** V8-A0 {100 * deep['top1']:.1f} vs V4-A0 "
                    f"{100 * shallow['top1']:.1f} → {verdict}"]
    else:
        out += ["", "**Depth gate (spec §3):** pending"]

    a2, v4 = im100("V8-A2"), im100("V4-A0")
    if a2 and v4:
        gap = abs(100 * (a2["top1"] - v4["top1"]))
        # top1 is correct/N_images, so an exact 1.0-point gap (e.g. 50/5000 images) can land as
        # 0.9999999999999953 in float — compare with a tolerance so a mathematically-exact gap
        # always triggers regardless of how the subtraction happens to round.
        follow = ("triggered — run seeds 1338/1339 for V8-A2, V4-A0 and V8-A1u4"
                  if gap >= 1.0 - 1e-9 else "not triggered — reported as no difference detected at 1 seed")
        # Two decimals here (unlike the pairs table's one) so the printed number never contradicts
        # the decision next to it — e.g. a genuine 0.96-point gap must not read as "1.0 points".
        out += ["", f"**Follow-up seed rule (spec §3):** |Δ| = {gap:.2f} points → {follow}"]
    else:
        out += ["", "**Follow-up seed rule (spec §3):** pending"]

    out += _protocol_section(manifests or {})
    return "\n".join(out) + "\n"


def _load_manifests(runs_dir: Path, seed: int) -> dict[str, dict | None]:
    """One manifest per arm for `seed`, or None where the run hasn't landed (or launched) yet.
    Manifests are frozen write-once files (spec 2026-09-16 §8.2 / `hallm.manifest`), so reading
    them here is safe even while the training queue is running."""
    manifests: dict[str, dict | None] = {}
    for arm in ARMS:
        p = runs_dir / f"{arm}-s{seed}" / "manifest.json"
        if not p.exists():
            manifests[arm] = None
            continue
        try:
            manifests[arm] = json.loads(p.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            manifests[arm] = None
    return manifests


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--runs-dir", default="runs/vision")
    ap.add_argument("--seed", type=int, default=1337)
    args = ap.parse_args()
    rows = read_run_results(Path(args.results) / "runs")
    manifests = _load_manifests(Path(args.runs_dir), args.seed)
    path = Path(args.results) / "reports" / "vision.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    text = (vision_report(rows, seed=args.seed, manifests=manifests)
           + f"\n<!-- built {stamp} from {len(rows)} run(s) -->\n")
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
