"""Regenerate every comparison table from per-run result files.

Idempotent and disposable: delete results/reports/*.md and re-run to rebuild. Nothing here is a
source of truth — results/runs/<run-id>.json is.

Usage: uv run python scripts/build_reports.py [--results results]
"""

from __future__ import annotations

import argparse
import math
from datetime import datetime, timezone
from pathlib import Path

from hallm.reports import (hc_verdict, hl_verdict, hs_verdict, index_runs, mean_se, paired,
                            parse_probe_id, parse_run_id, regress, tax)
from hallm.results import read_run_results

STAMP = "<!-- GENERATED by scripts/build_reports.py from results/runs/*.json — do not edit -->"
# Per-layer non-embedding storage in units of d^2: attention 4, FFN 8.
STORAGE_SAVED = {"A2": 50.0, "A2ffn": 33.3, "A2attn": 16.7, "A1": 87.5, "A3": 93.7}

# The campaign metric. Until 2026-09-14 the runner scored val.bin and called it test_ppl; result
# files now say val_ppl, and a true test_ppl exists wherever a checkpoint survives (splits.md).
METRIC = "val_ppl"

# Fixed-storage comparisons (spec 2026-09-14 §4.4), paired by seed. "iso-storage" (H-C): a shared
# arm vs the unshared model storing about the same weights. "matched" (H-L): two sharing kinds at
# identical storage AND identical compute.
COMPARISONS = [
    ("L8-A2", "L4-A0", "iso-storage"),
    ("L16-A2", "L8-A0", "iso-storage"),
    ("L8-A2attn", "L7-A0", "iso-storage"),
    ("L9-A2attn", "L8-A0", "iso-storage"),
    ("L10-A2attn", "L8-A0", "iso-storage"),
    ("L8-A1u4", "L4-A0", "iso-storage"),
    ("L16-A1u8", "L8-A0", "iso-storage"),
    ("L8-A1u4", "L8-A2", "matched"),
    ("L16-A1u8", "L16-A2", "matched"),
]


def check_val_ppl_present(rows: list[dict]) -> None:
    """Every results/runs row must carry `val_ppl` (the 2026-09-14 migration renamed the pre-existing
    `test_ppl` field to it). A row that still lacks it predates that migration and would otherwise
    surface as a bare KeyError deep inside some build_* function — fail clearly here instead."""
    missing = sorted(r["run"] for r in rows if "run" in r and METRIC not in r)
    if missing:
        raise ValueError(
            f"{len(missing)} run(s) missing '{METRIC}' — pre-migration result file(s): "
            f"{', '.join(missing)}. Run `uv run python scripts/migrate_ppl_split.py` first."
        )


def _by_id(rows: list[dict]) -> dict[str, dict]:
    return {r["run"]: r for r in rows if "run" in r}


def _first(by_id: dict[str, dict], prefix: str) -> dict | None:
    return next((by_id[k] for k in sorted(by_id) if k.startswith(prefix + "-s") and parse_run_id(k)), None)


def _side(by_id: dict[str, dict], a: str, b: str, field: str, nd: int = 2, scale: float = 1.0) -> str:
    vals = []
    for prefix in (a, b):
        r = _first(by_id, prefix)
        v = r.get(field) if r else None
        vals.append(_f(v * scale if v is not None else None, nd))
    return " / ".join(vals)


def _total_mem_side(by_id: dict[str, dict], a: str, b: str, kv_field: str) -> str:
    """Total inference memory (bf16 weights + KV cache) in MB, one side per comparison arm — the
    same formula build_probes uses."""
    vals = []
    for prefix in (a, b):
        r = _first(by_id, prefix)
        w = r.get("weight_bytes_bf16") if r else None
        kv = r.get(kv_field) if r else None
        total = (w + kv) / 1e6 if w is not None and kv is not None else None
        vals.append(_f(total, 1))
    return " / ".join(vals)


def _f(v, nd=2, dash="—"):
    return dash if v is None or (isinstance(v, float) and math.isnan(v)) else f"{v:.{nd}f}"


def build_ladder(rows: list[dict]) -> str:
    idx = index_runs(rows)
    L = [STAMP, "# Scaling ladder — sharing tax vs depth", "",
         "Tax = (PPL_shared - PPL_unshared) / PPL_unshared, measured **within** a seed pair.", "",
         "| rung | seed | A0 (unshared) | A2 (W+Wt) | tax % |", "|---|---|---|---|---|"]
    per_rung: dict[int, list[float]] = {}
    pts_x: list[float] = []
    pts_y: list[float] = []
    for (depth, seed) in sorted(idx):
        arms = idx[(depth, seed)]
        a0, a2 = arms.get("A0"), arms.get("A2")
        if not a0:
            continue
        if not a2:
            L.append(f"| L{depth} | {seed} | {a0[METRIC]:.4f} | *(pending)* | — |")
            continue
        t = tax(a2[METRIC], a0[METRIC])
        per_rung.setdefault(depth, []).append(t)
        nonemb = a0.get("non_embedding_params_M")
        if nonemb:
            pts_x.append(math.log2(nonemb))
            pts_y.append(t)
        L.append(f"| L{depth} | {seed} | {a0[METRIC]:.4f} | {a2[METRIC]:.4f} | **{t:.2f}** |")

    L += ["", "## Per-rung summary", "",
          "| rung | n seeds | mean tax % | SE |", "|---|---|---|---|"]
    for depth in sorted(per_rung):
        m, se = mean_se(per_rung[depth])
        L.append(f"| L{depth} | {len(per_rung[depth])} | {m:.2f} | {_f(se)} |")

    reg = regress(pts_x, pts_y)
    L += ["", "## H-S: does the tax decay with scale?", "",
          "Pre-registered decision rule (program spec P3): regress tax on log2(non-embedding params);",
          "**supported** iff the slope's 95% CI excludes zero on the negative side.", ""]
    if reg["n"] >= 3:
        L += [f"- points: **{reg['n']}** pairs",
              f"- slope: **{reg['slope']:.2f} pp** per doubling of non-embedding params",
              f"- 95% CI: [{reg['ci_lo']:.2f}, {reg['ci_hi']:.2f}]  (df={reg['df']})",
              f"- **verdict: {hs_verdict(reg)}**"]
        if reg["slope"] < 0 and reg.get("intercept") is not None:
            need = 2 ** ((reg["intercept"] - 2.0) / -reg["slope"]) if reg["slope"] else float("inf")
            L += ["", f"Extrapolated non-embedding size for a <2% tax: **{need:,.0f}M params**. "
                      "Reported to keep the decay honest — the ladder characterises a rate, it does "
                      "not lead to the viability gate."]
    else:
        L.append(f"- insufficient data ({reg['n']} complete pairs; need 3)")
    return "\n".join(L) + "\n"


def build_mechanism(rows: list[dict]) -> str:
    """P1: which sublayer's sharing causes the tax? Verdicts are per rung, never pooled."""
    idx = index_runs(rows)
    L = [STAMP, "# Mechanism decomposition (P1) — where does the tax come from?", "",
         "FFN sharing has a genuine nonlinearity between W and W-transpose (strong column-space",
         "argument). Attention sharing has K and V both linear in the same x, and couples the QK and",
         "OV circuits (weak path, risk R1). Pre-registered: tax(attn-only) > tax(ffn-only) by >2pp.",
         "", "| rung | seed | arm | PPL | tax % | storage saved % | cost per % saved |",
         "|---|---|---|---|---|---|---|"]
    per_arm: dict[tuple[int, str], list[float]] = {}
    for (depth, seed) in sorted(idx):
        arms = idx[(depth, seed)]
        a0 = arms.get("A0")
        if not a0:
            continue
        for tag in ("A2", "A2ffn", "A2attn"):
            row = arms.get(tag)
            if not row:
                continue
            t = tax(row[METRIC], a0[METRIC])
            per_arm.setdefault((depth, tag), []).append(t)
            saved = STORAGE_SAVED.get(tag)
            ratio = t / saved if saved else float("nan")
            L.append(f"| L{depth} | {seed} | {tag} | {row[METRIC]:.4f} | {t:.2f} | "
                     f"{_f(saved, 1)} | {_f(ratio, 3)} |")
    if not per_arm:
        L += ["| — | — | — | — | — | — | — |", "", "*No ablation runs complete yet.*"]
        return "\n".join(L) + "\n"

    L += ["", "## Verdict, per rung", "",
          "Rungs are never pooled: pooling lets one rung's ordering overwrite another's (the pooled",
          "table once named A2ffn against the pre-registered L8 reading, A2attn).", ""]
    for depth in sorted({d for d, _ in per_arm}):
        ffn, attn, both = (per_arm.get((depth, t)) for t in ("A2ffn", "A2attn", "A2"))
        L += [f"### L{depth}", ""]
        if not (ffn and attn):
            L += ["- decomposition incomplete at this rung: need both A2ffn and A2attn.", ""]
            continue
        mf, _ = mean_se(ffn)
        ma, _ = mean_se(attn)
        L.append(f"- mean tax: FFN-only **{mf:.2f}%**, attn-only **{ma:.2f}%** "
                 f"(difference {ma - mf:+.2f} pp; n = {len(ffn)} / {len(attn)})")
        L.append(f"- **H-M1 ({'supported' if ma - mf > 2 else 'not supported'})**: "
                 "attention sharing costs more than FFN sharing by >2pp")
        if both:
            mb, _ = mean_se(both)
            L.append(f"- **H-M2 ({'supported' if abs(mb - (mf + ma)) < 2 else 'not supported'})**: "
                     f"taxes are additive — A2 {mb:.2f}% vs ffn+attn {mf + ma:.2f}%")
        best = min(("A2ffn", mf / STORAGE_SAVED["A2ffn"]), ("A2attn", ma / STORAGE_SAVED["A2attn"]),
                   key=lambda kv: kv[1])
        L += [f"- best cost-per-%-storage-saved: **{best[0]}** at {best[1]:.3f}", ""]
    return "\n".join(L) + "\n"


def build_memory(rows: list[dict]) -> str:
    L = [STAMP, "# Memory accounting", "",
         "Sharing compresses **weights only** — the KV cache is 2*d*L per token regardless. This is",
         "why re-investing shared weights into depth pays the saving back in cache.", "",
         "| run | weight MB (bf16) | KV MB @ctx512 b1 | KV MB @ctx2048 b8 | weight share @ctx512 |",
         "|---|---|---|---|---|"]
    any_row = False
    for r in rows:
        # Same gate as index_runs: probe runs (4-part ids) never enter a generated table.
        if "weight_bytes_bf16" not in r or not parse_run_id(r.get("run", "")):
            continue
        any_row = True
        L.append(f"| {r['run']} | {r['weight_bytes_bf16']/1e6:.1f} | "
                 f"{r['kv_bytes_ctx512_b1']/1e6:.1f} | {r['kv_bytes_ctx2048_b8']/1e6:.1f} | "
                 f"{r['weight_frac_of_total_ctx512_b1']*100:.1f}% |")
    if not any_row:
        L.append("| — | — | — | — | — |")
        L += ["", "*No run carries measured memory yet (pre-P0 runs did not record it).*"]
    return "\n".join(L) + "\n"


def build_iso_storage(rows: list[dict], metric: str = METRIC) -> str:
    """F3: spec §1 requires weights + KV memory at ctx512×1 AND ctx2048×8 for both sides, so both
    total-memory points are shown (weight_bytes_bf16 + kv bytes, the same formula build_probes uses)
    rather than KV alone at just one of the two points."""
    by_id = _by_id(rows)
    L = [STAMP, "# Fixed storage — does extra compute through sharing pay?", "",
         "Spec 2026-09-14 §4.4. Δ% = (PPL_a − PPL_b) / PPL_b within a seed; negative means a is better.",
         "**iso-storage** (H-C): shared arm vs the unshared model storing about the same weights —",
         "supported iff every paired seed is negative. **matched** (H-L): two sharing kinds at identical",
         "storage and compute — a winner only if all 3 seeds agree in sign and |mean| > 2 SE.",
         f"Metric: `{metric}`. Extra depth grows the KV cache, so total inference memory (bf16 weights",
         "+ KV cache) is shown for both sides at both fixed-storage points (spec §1: ctx512×1 and",
         "ctx2048×8).", "",
         "| a | b | kind | stored M a / b | GFLOPs a / b | total MB @512×1 a / b | "
         "total MB @2048×8 a / b | n | Δ% per seed | mean Δ% | SE | verdict |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for a, b, kind in COMPARISONS:
        diffs = [d for _, d in paired(by_id, a, b, metric)]
        m, se = mean_se(diffs)
        verdict = hc_verdict(diffs) if kind == "iso-storage" else hl_verdict(diffs, a, b)
        per_seed = ", ".join(f"{d:+.2f}" for d in diffs) or "—"
        L.append(f"| {a} | {b} | {kind} | {_side(by_id, a, b, 'non_embedding_params_M')} | "
                 f"{_side(by_id, a, b, 'fwd_gflops', 1)} | "
                 f"{_total_mem_side(by_id, a, b, 'kv_bytes_ctx512_b1')} | "
                 f"{_total_mem_side(by_id, a, b, 'kv_bytes_ctx2048_b8')} | "
                 f"{len(diffs)} | {per_seed} | {_f(m)} | {_f(se)} | {verdict} |")
    return "\n".join(L) + "\n"


def build_probes(rows: list[dict]) -> str:
    L = [STAMP, "# Off-ladder runs (4-part IDs)", "",
         "LR probes, P4 frontier widths and other corpora — kept out of every ladder table. Shown with",
         "total inference memory (bf16 weights + KV cache), the axis P4's rule is scored on.", "",
         f"| run | arm | suffix | stored non-emb M | {METRIC} | weights MB | total MB @512×1 | total MB @2048×8 |",
         "|---|---|---|---|---|---|---|---|"]
    any_row = False
    for r in rows:
        p = parse_probe_id(r.get("run", ""))
        if not p:
            continue
        any_row = True
        w = r.get("weight_bytes_bf16")
        t1 = (w + r["kv_bytes_ctx512_b1"]) / 1e6 if w and "kv_bytes_ctx512_b1" in r else None
        t8 = (w + r["kv_bytes_ctx2048_b8"]) / 1e6 if w and "kv_bytes_ctx2048_b8" in r else None
        L.append(f"| {r['run']} | {p['arm']} | {p['suffix']} | {_f(r.get('non_embedding_params_M'))} | "
                 f"{_f(r.get(METRIC), 4)} | {_f(w / 1e6 if w else None, 1)} | {_f(t1, 1)} | {_f(t8, 1)} |")
    if not any_row:
        L.append("| — | — | — | — | — | — | — | — |")
    return "\n".join(L) + "\n"


def build_split_check(rows: list[dict]) -> str:
    """F2: the val and test verdicts must be computed on the SAME seeds — a seed with val_ppl but
    no test_ppl (or vice versa) must not be allowed to silently drop out of only one side, which
    could make two verdicts disagree for no reason but mismatched sample sizes."""
    by_id = _by_id(rows)
    L = [STAMP, "# Validation vs test split", "",
         "Until 2026-09-14 every PPL was computed on WikiText-103 **validation** and labelled test.",
         "`val_ppl` stays the campaign metric (every run has it; nothing was tuned on it). `test_ppl`",
         "exists where a checkpoint survives. Both verdicts below are computed on the SAME seeds —",
         "only seeds where both runs of the pair carry both `val_ppl` and `test_ppl` — so a seed",
         "missing on one side can't manufacture a disagreement. The first verdict column keeps the",
         "full val-seed headline visible.", "",
         "| a | b | kind | verdict (val, all seeds) | n matched | val verdict (matched) | "
         "test verdict (matched) | same |",
         "|---|---|---|---|---|---|---|---|"]
    for a, b, kind in COMPARISONS:
        v_by_seed = dict(paired(by_id, a, b, "val_ppl"))
        t_by_seed = dict(paired(by_id, a, b, "test_ppl"))
        v_all = list(v_by_seed.values())
        vv_all = hc_verdict(v_all) if kind == "iso-storage" else hl_verdict(v_all, a, b)

        matched = sorted(set(v_by_seed) & set(t_by_seed))
        if matched:
            v_m = [v_by_seed[s] for s in matched]
            t_m = [t_by_seed[s] for s in matched]
            vv_m, tv_m = ((hc_verdict(v_m), hc_verdict(t_m)) if kind == "iso-storage"
                          else (hl_verdict(v_m, a, b), hl_verdict(t_m, a, b)))
            same = "yes" if vv_m == tv_m else "**NO**"
        else:
            # Absence of matched data is not a verdict that depends on the split.
            vv_m = tv_m = "no test data"
            same = "—"
        L.append(f"| {a} | {b} | {kind} | {vv_all} | {len(matched)} | {vv_m} | {tv_m} | {same} |")
    return "\n".join(L) + "\n"


# Track 1 probe metrics (spec 2026-09-14 §4.2, amended 2026-09-14) → higher_is_better
PROBE_METRICS = {"lambada_acc": True, "blimp_macro": True, "copy_gain": True,
                 "late_loss": False, "rare_loss": False}

# Per-metric unit for paired()'s higher_is_better diff. Accuracies live in [0, 1], so the default
# scale (100, see paired()) turns the diff into percentage points. copy_gain is already in nats —
# scaling it by 100 would print centi-nats, so it keeps a plain difference (scale 1).
PROBE_SCALE = {"copy_gain": 1.0}


def build_capability(cap_rows: list[dict]) -> str:
    by_id = _by_id(cap_rows)
    L = [STAMP, "# Probes (Track 1) — H-R", "",
         "Spec 2026-09-14 §4.2/§4.4: the iso-storage.md rules applied per probe metric. Δ < 0 means a is",
         "better (relative % for losses, percentage points for accuracies, nats for copy_gain).", "",
         "| run | " + " | ".join(PROBE_METRICS) + " |", "|---|" + "---|" * len(PROBE_METRICS)]
    for rid in sorted(by_id):
        L.append(f"| {rid} | " + " | ".join(_f(by_id[rid].get(m), 4) for m in PROBE_METRICS) + " |")
    L += ["", "## Verdicts", "", "| a | b | kind | metric | n | mean Δ | verdict |",
          "|---|---|---|---|---|---|---|"]
    for a, b, kind in COMPARISONS:
        for m, hib in PROBE_METRICS.items():
            diffs = [d for _, d in paired(by_id, a, b, m, higher_is_better=hib,
                                          scale=PROBE_SCALE.get(m, 100.0))]
            if not diffs:
                continue
            mean, _ = mean_se(diffs)
            v = hc_verdict(diffs) if kind == "iso-storage" else hl_verdict(diffs, a, b)
            L.append(f"| {a} | {b} | {kind} | {m} | {len(diffs)} | {mean:+.2f} | {v} |")
    return "\n".join(L) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="results")
    args = ap.parse_args()
    results = Path(args.results)
    rows = read_run_results(results / "runs")
    check_val_ppl_present(rows)
    cap_rows = read_run_results(results / "capability")
    out = results / "reports"
    out.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    for name, text in (("ladder.md", build_ladder(rows)),
                       ("mechanism.md", build_mechanism(rows)),
                       ("memory.md", build_memory(rows)),
                       ("iso-storage.md", build_iso_storage(rows)),
                       ("probes.md", build_probes(rows)),
                       ("splits.md", build_split_check(rows)),
                       ("capability.md", build_capability(cap_rows))):
        (out / name).write_text(text + f"\n<!-- built {stamp} from {len(rows)} run(s) -->\n",
                                encoding="utf-8")
        print(f"wrote {out / name}")


if __name__ == "__main__":
    main()
